import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  intro: [{type: 'autogenerated', dirName: 'intro'}],
  getStarted: [{type: 'autogenerated', dirName: 'get-started'}],
  contribute: [{type: 'autogenerated', dirName: 'contribute'}],
};

export default sidebars;
