import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  devDocs: [{type: 'autogenerated', dirName: 'dev-docs'}],
  restApi: [{type: 'autogenerated', dirName: 'rest-api'}],
  contribute: [{type: 'autogenerated', dirName: 'contribute'}],
};

export default sidebars;
