name: Tests Workflow

on:
  pull_request:
    branches: [master, development]
    paths-ignore:
      - 'templates/**'
      - 'swagger/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  all-in-one:
    name: 'All-in-one (node: 18)'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Dependencies install
        uses: ./.github/actions/yarn-nm-install
      - name: Docs build
        uses: ./.github/actions/run-build
      - name: Docs lint
        uses: ./.github/actions/run-lints